// perf-optimize/vue-lab/src/demos/InputStormDemo.vue
<script setup lang="ts">
/**
 * 案例 6：输入风暴
 * 🐛 每次按键同步触发 3 万条数据过滤 + 大列表 patch，输入延迟肉眼可见。
 * 💡 方向：防抖/节流、v-memo、避免 v-model 直接驱动大列表、过滤下沉 Worker。
 */
import { computed, ref } from 'vue'
import { heavyFilterSort, makeRows, type Row } from './data'
import { fmt, useUpdateTime } from '../perf'
import Metrics from '../components/Metrics.vue'
import BugTip from '../components/BugTip.vue'

const ROWS = makeRows(30000)
const keyword = ref('')
const latency = ref(0)
const optimized = ref(false)
const { cost } = useUpdateTime()

const rawList = computed(() => heavyFilterSort(ROWS, keyword.value, 'score'))
const debouncedKeyword = ref('')
let timer = 0
const debouncedList = computed(() => heavyFilterSort(ROWS, debouncedKeyword.value, 'score'))

function onInput(e: Event) {
  const value = (e.target as HTMLInputElement).value
  const t0 = performance.now()
  keyword.value = value
  if (optimized.value) {
    clearTimeout(timer)
    timer = window.setTimeout(() => {
      debouncedKeyword.value = value
      latency.value = performance.now() - t0
    }, 260)
  } else {
    debouncedKeyword.value = value
    latency.value = performance.now() - t0
  }
}

const list = computed<Row[]>(() => (optimized.value ? debouncedList.value : rawList.value))
</script>

<template>
  <Metrics
    :items="[
      { label: '按键响应延迟', value: `${fmt(latency)} ms`, warn: latency > 50 },
      { label: '上次更新耗时', value: `${fmt(cost)} ms`, warn: cost > 30 },
      { label: '结果条数', value: list.length.toLocaleString() },
      { label: '模式', value: optimized ? '防抖（已优化）' : '直接过滤（有问题）' },
    ]"
  />

  <div class="toolbar">
    <input class="input" :value="keyword" @input="onInput" placeholder="快速连续输入，例如 用户-123" />
    <label class="switch">
      <input type="checkbox" v-model="optimized" />
      启用防抖（对照）
    </label>
  </div>

  <BugTip>
    <template #bug>
      <code>v-model</code> 直接绑定大列表的过滤条件：每个按键都要同步跑一次 3 万条过滤 + 完整的 patch，
      输入被低优先级渲染拖死。
    </template>
    <template #tip>
      ① 防抖/节流（<code>lodash/debounce</code>）；② 列表项加 <code>v-memo="[item.id, item.score]"</code> 减少 diff；
      ③ 输入值用本地 ref，过滤结果再同步；④ 大数据过滤放 Web Worker 或预建倒排索引。
    </template>
  </BugTip>

  <div class="list">
    <div class="list-row" v-for="r in list.slice(0, 100)" :key="r.id">
      <span class="col-name">{{ r.name }}</span>
      <span class="col-dept">{{ r.dept }}</span>
      <span class="col-score">{{ r.score }}</span>
    </div>
  </div>
</template>

// perf-optimize/react-lab/src/demos/InputStormDemo.tsx
import { useState } from 'react'
import { heavyFilterSort, makeRows } from './data'
import { fmt, useRenderTime } from '../perf'
import { Bug, Metrics, Tip, Toolbar } from '../ui'

const ROWS = makeRows(30000)

/**
 * 案例 6：输入风暴
 * 🐛 每敲一个字符都同步触发 3 万条数据过滤 + 大列表重渲染，输入延迟肉眼可见。
 * 💡 方向：受控转非受控、debounce/throttle、useDeferredValue + memo、Web Worker 过滤。
 */
export default function InputStormDemo() {
  const [keyword, setKeyword] = useState('')
  const [inputLatency, setInputLatency] = useState(0)
  const renderTime = useRenderTime()

  const handleChange = (value: string) => {
    const t0 = performance.now()
    setKeyword(value)
    // 🐛 同步 setState，React 会在同一帧内完成昂贵的过滤与渲染，这里量到的就是「按键到提交」的成本
    requestAnimationFrame(() => setInputLatency(performance.now() - t0))
  }

  const list = heavyFilterSort(ROWS, keyword, 'score')

  return (
    <div>
      <Metrics
        items={[
          { label: '按键响应延迟', value: `${fmt(inputLatency)} ms`, warn: inputLatency > 50 },
          { label: '上次渲染耗时', value: `${fmt(renderTime)} ms`, warn: renderTime > 30 },
          { label: '结果条数', value: list.length.toLocaleString() },
        ]}
      />
      <Toolbar>
        <input
          className="input"
          value={keyword}
          onChange={(e) => handleChange(e.target.value)}
          placeholder="连续快速输入试试，例如 用户-12"
        />
        <button className="btn" onClick={() => handleChange('')}>
          清空
        </button>
      </Toolbar>

      <Bug>
        输入是最高优先级交互，却绑定了 O(n) 过滤 + 大列表重渲染：每个按键都要等几十毫秒，连续输入直接卡成幻灯片，
        且每次输入都会产生一次完整的 commit。
      </Bug>
      <Tip>
        ① 防抖/节流（<code>lodash/debounce</code> 或自实现）；② 低优先级更新 <code>useDeferredValue(keyword)</code> 配合
        <code>memo</code> 列表项；③ 输入框改非受控 + <code>ref</code>；④ 大数据过滤放 Web Worker / 预建索引。
      </Tip>

      <div className="list">
        {list.slice(0, 100).map((r) => (
          <div className="list-row" key={r.id}>
            <span className="col-name">{r.name}</span>
            <span className="col-dept">{r.dept}</span>
            <span className="col-score">{r.score}</span>
          </div>
        ))}
      </div>
    </div>
  )
}
