// perf-optimize/react-lab/src/demos/LongListDemo.tsx
import { useState } from 'react'
import { makeRows, type Row } from './data'
import { fmt, useRenderTime } from '../perf'
import { Bug, Field, Metrics, Tip, Toolbar } from '../ui'

/**
 * 案例 1：长列表全量渲染
 * 🐛 一次性把 N 万条数据渲染成真实 DOM，首屏/交互都会卡死。
 * 💡 方向：虚拟滚动（react-window / react-virtuoso / 手写）、分页、Content-Visibility。
 */
export default function LongListDemo() {
  const [count, setCount] = useState(5000)
  const [rows, setRows] = useState<Row[]>(() => makeRows(5000))
  const [buildMs, setBuildMs] = useState(0)
  const [keyword, setKeyword] = useState('')
  const renderTime = useRenderTime()

  const regenerate = () => {
    setKeyword('')
    const t0 = performance.now()
    const next = makeRows(count)
    setBuildMs(performance.now() - t0)
    setRows(next)
  }

  // 🐛 不做任何窗口化：所有数据一次性渲染成 DOM
  const visible = keyword ? rows.filter((r) => r.name.includes(keyword)) : rows

  return (
    <div>
      <Metrics
        items={[
          { label: '数据条数', value: rows.length.toLocaleString() },
          { label: 'DOM 行数', value: rows.length.toLocaleString(), warn: rows.length > 5000 },
          { label: '数据生成耗时', value: `${fmt(buildMs)} ms` },
          { label: '上次渲染耗时', value: `${fmt(renderTime)} ms`, warn: renderTime > 100 },
        ]}
      />
      <Toolbar>
        <Field label={`条数 ${count.toLocaleString()}`}>
          <input
            type="range"
            min={1000}
            max={100000}
            step={1000}
            value={count}
            onChange={(e) => setCount(Number(e.target.value))}
          />
        </Field>
        <button className="btn" onClick={regenerate}>
          生成并渲染
        </button>
        <Field label="搜索（每次输入都会全量过滤）">
          <input value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="输入 用户-1" />
        </Field>
      </Toolbar>

      <Bug>
        可视区只有 300 行，却把 <b>全部 {rows.length.toLocaleString()} 行</b> 都渲染成了 DOM：创建节点、样式计算、布局、绘制全部线性上涨，
        滚动与输入都会掉帧。
      </Bug>
      <Tip>
        只渲染可视区（虚拟列表 / 窗口化），或 <code>content-visibility: auto</code> + 分页；搜索走索引/Web Worker，避免在主线程 filter 全量数据。
      </Tip>

      <div className="list">
        {visible.map((r) => (
          <div className="list-row" key={r.id}>
            <span className="avatar" style={{ background: `hsl(${r.id % 360} 60% 45%)` }}>
              {r.name.slice(-1)}
            </span>
            <span className="col-name">{r.name}</span>
            <span className="col-email">{r.email}</span>
            <span className="col-dept">{r.dept}</span>
            <span className="col-tag">{r.tag}</span>
            <span className="col-bar">
              <i style={{ width: `${r.score}%` }} />
            </span>
          </div>
        ))}
        {rows.length > 20 && <div className="list-more">…… 以上 {visible.length.toLocaleString()} 行全部是真实 DOM，可视区只能看到约 20 行</div>}
      </div>
    </div>
  )
}

// perf-optimize/vue-lab/src/demos/LongListDemo.vue
<script setup lang="ts">
/**
 * 案例 1：长列表全量渲染
 * 🐛 1 万条数据一次性 v-for 成真实 DOM，首屏与交互全部卡死。
 * 💡 方向：虚拟滚动（vue-virtual-scroller / @tanstack/vue-virtual / 手写）、分页、content-visibility。
 */
import { ref } from 'vue'
import { makeRows, type Row } from './data'
import { fmt, useUpdateTime } from '../perf'
import Metrics from '../components/Metrics.vue'
import BugTip from '../components/BugTip.vue'

const count = ref(5000)
const rows = ref<Row[]>(makeRows(5000))
const keyword = ref('')
const buildMs = ref(0)
const { cost } = useUpdateTime()

function regenerate() {
  const t0 = performance.now()
  rows.value = makeRows(count.value)
  buildMs.value = performance.now() - t0
}
</script>

<template>
  <Metrics
    :items="[
      { label: '数据条数', value: rows.length.toLocaleString() },
      { label: 'DOM 行数', value: rows.length.toLocaleString(), warn: rows.length > 3000 },
      { label: '数据生成耗时', value: `${fmt(buildMs)} ms` },
      { label: '上次更新耗时', value: `${fmt(cost)} ms`, warn: cost > 100 },
    ]"
  />

  <div class="toolbar">
    <label class="field">
      <span>条数 {{ count.toLocaleString() }}</span>
      <input type="range" min="1000" max="100000" step="1000" v-model.number="count" />
    </label>
    <button class="btn" @click="regenerate">生成并渲染</button>
    <input class="input" v-model="keyword" placeholder="输入关键字（每次输入全量过滤）" />
  </div>

  <BugTip>
    <template #bug>
      可视区只有约 20 行，却把 <b>{{ rows.length.toLocaleString() }}</b> 行全部渲染成 DOM：patch、样式计算、布局、绘制成本线性上涨。
    </template>
    <template #tip>
      只渲染可视区（虚拟列表 / 窗口化），或 <code>content-visibility: auto</code> + 分页；大数据用 <code>shallowRef</code> 避免深度代理，过滤下沉到 Worker。
    </template>
  </BugTip>

  <div class="list">
    <div class="list-row" v-for="r in keyword ? rows.filter((x) => x.name.includes(keyword)) : rows" :key="r.id">
      <span class="avatar" :style="{ background: `hsl(${r.id % 360} 60% 45%)` }">{{ r.name.slice(-1) }}</span>
      <span class="col-name">{{ r.name }}</span>
      <span class="col-email">{{ r.email }}</span>
      <span class="col-dept">{{ r.dept }}</span>
      <span class="col-tag">{{ r.tag }}</span>
      <span class="col-bar"><i :style="{ width: `${r.score}%` }" /></span>
    </div>
  </div>
</template>
